services:
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:4000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3001
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro

  backend:
    build: ./backend
    ports:
      - "3001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=http://localhost:4000
    restart: unless-stopped
