services:
  - type: web
    name: skin-tone-variator
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://skin-tone-variator.onrender.com
